//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Funcular.DomainTools.Applications.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\temp")]
        public string OutputDirectory {
            get {
                return ((string)(this["OutputDirectory"]));
            }
            set {
                this["OutputDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Entities")]
        public string EntityNamespace {
            get {
                return ((string)(this["EntityNamespace"]));
            }
            set {
                this["EntityNamespace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Providers")]
        public string DataProviderNamespace {
            get {
                return ((string)(this["DataProviderNamespace"]));
            }
            set {
                this["DataProviderNamespace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AppendDbSchemaToNamepaces {
            get {
                return ((bool)(this["AppendDbSchemaToNamepaces"]));
            }
            set {
                this["AppendDbSchemaToNamepaces"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EntitiesInherit {
            get {
                return ((string)(this["EntitiesInherit"]));
            }
            set {
                this["EntitiesInherit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EntitiesImplementInterfaces {
            get {
                return ((string)(this["EntitiesImplementInterfaces"]));
            }
            set {
                this["EntitiesImplementInterfaces"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SqlTextCommand {
            get {
                return ((string)(this["SqlTextCommand"]));
            }
            set {
                this["SqlTextCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GenerateFluentEFMappings {
            get {
                return ((bool)(this["GenerateFluentEFMappings"]));
            }
            set {
                this["GenerateFluentEFMappings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GenerateCrmSpecificProperties {
            get {
                return ((bool)(this["GenerateCrmSpecificProperties"]));
            }
            set {
                this["GenerateCrmSpecificProperties"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ImplementIdGenerator {
            get {
                return ((bool)(this["ImplementIdGenerator"]));
            }
            set {
                this["ImplementIdGenerator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"\"")]
        public string GeneratedIdDataType {
            get {
                return ((string)(this["GeneratedIdDataType"]));
            }
            set {
                this["GeneratedIdDataType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"\"")]
        public string IdGenerationFunc {
            get {
                return ((string)(this["IdGenerationFunc"]));
            }
            set {
                this["IdGenerationFunc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection SavedConnectionStrings {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SavedConnectionStrings"]));
            }
            set {
                this["SavedConnectionStrings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("new;_")]
        public string AdditionalCollapseTokens {
            get {
                return ((string)(this["AdditionalCollapseTokens"]));
            }
            set {
                this["AdditionalCollapseTokens"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseAutomaticProperties {
            get {
                return ((bool)(this["UseAutomaticProperties"]));
            }
            set {
                this["UseAutomaticProperties"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Base")]
        public string AdditionalTokenFind {
            get {
                return ((string)(this["AdditionalTokenFind"]));
            }
            set {
                this["AdditionalTokenFind"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ExtensionBase")]
        public string AdditionalTokenReplace {
            get {
                return ((string)(this["AdditionalTokenReplace"]));
            }
            set {
                this["AdditionalTokenReplace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PrimaryKeyGetsNamedId {
            get {
                return ((bool)(this["PrimaryKeyGetsNamedId"]));
            }
            set {
                this["PrimaryKeyGetsNamedId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Usings {
            get {
                return ((string)(this["Usings"]));
            }
            set {
                this["Usings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EntityAttributes {
            get {
                return ((string)(this["EntityAttributes"]));
            }
            set {
                this["EntityAttributes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MappingAttributes {
            get {
                return ((string)(this["MappingAttributes"]));
            }
            set {
                this["MappingAttributes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SqlConnectionString {
            get {
                return ((string)(this["SqlConnectionString"]));
            }
            set {
                this["SqlConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Company.Solution")]
        public string BaseNamespace {
            get {
                return ((string)(this["BaseNamespace"]));
            }
            set {
                this["BaseNamespace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProjectFile {
            get {
                return ((string)(this["ProjectFile"]));
            }
            set {
                this["ProjectFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AddColumnNameAttributes {
            get {
                return ((bool)(this["AddColumnNameAttributes"]));
            }
            set {
                this["AddColumnNameAttributes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GenerateInheritingBusinessObjects {
            get {
                return ((bool)(this["GenerateInheritingBusinessObjects"]));
            }
            set {
                this["GenerateInheritingBusinessObjects"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RemoveDboFromOutputFolderPath {
            get {
                return ((bool)(this["RemoveDboFromOutputFolderPath"]));
            }
            set {
                this["RemoveDboFromOutputFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Entity")]
        public string EntitySuffix {
            get {
                return ((string)(this["EntitySuffix"]));
            }
            set {
                this["EntitySuffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EntitiesSubdirectory {
            get {
                return ((string)(this["EntitiesSubdirectory"]));
            }
            set {
                this["EntitiesSubdirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BusinessObjectsSubdirectory {
            get {
                return ((string)(this["BusinessObjectsSubdirectory"]));
            }
            set {
                this["BusinessObjectsSubdirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BusinessObjectsNamespace {
            get {
                return ((string)(this["BusinessObjectsNamespace"]));
            }
            set {
                this["BusinessObjectsNamespace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AddDataAnnotationAttributes {
            get {
                return ((bool)(this["AddDataAnnotationAttributes"]));
            }
            set {
                this["AddDataAnnotationAttributes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TableNameStemIsInnerNamespace {
            get {
                return ((bool)(this["TableNameStemIsInnerNamespace"]));
            }
            set {
                this["TableNameStemIsInnerNamespace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EntitySubdirectory {
            get {
                return ((string)(this["EntitySubdirectory"]));
            }
            set {
                this["EntitySubdirectory"] = value;
            }
        }
    }
}
